import { DatabaseSchema } from "types/report";

export const staticData: DatabaseSchema[] = [
    {
      id: '1',
      userId: 'user1',
      type: 'loan',
      description: 'Took a personal loan',
      amount: 5000,
      date: '2025-01-01',
    },
    {
      id: '2',
      userId: 'user1',
      type: 'payment',
      description: 'Paid loan installment',
      amount: 1000,
      date: '2025-01-05',
    },
    {
      id: '3',
      userId: 'user1',
      type: 'contribution',
      description: 'Added to monthly savings',
      amount: 200,
      date: '2025-01-10',
    },
    {
      id: '4',
      userId: 'user2',
      type: 'loan',
      description: 'Took a business loan',
      amount: 10000,
      date: '2025-01-15',
    },
    {
      id: '5',
      userId: 'user2',
      type: 'payment',
      description: 'Paid partial loan installment',
      amount: 3000,
      date: '2025-01-20',
    },
    {
        id: '6',
        userId: 'user1',
        type: 'loan',
        description: 'Took a personal loan',
        amount: 5000,
        date: '2025-01-01',
      },
      {
        id: '7',
        userId: 'user1',
        type: 'payment',
        description: 'Paid loan installment',
        amount: 1000,
        date: '2025-01-05',
      },
      {
        id: '8',
        userId: 'user1',
        type: 'contribution',
        description: 'Added to monthly savings',
        amount: 200,
        date: '2025-01-10',
      },
      {
        id: '9',
        userId: 'user2',
        type: 'loan',
        description: 'Took a business loan',
        amount: 10000,
        date: '2025-01-15',
      },
      {
        id: '10',
        userId: 'user2',
        type: 'payment',
        description: 'Paid partial loan installment',
        amount: 3000,
        date: '2025-01-20',
      },
      {
        id: '11',
        userId: 'user1',
        type: 'loan',
        description: 'Took a personal loan',
        amount: 5000,
        date: '2025-01-01',
      },
      {
        id: '12',
        userId: 'user1',
        type: 'payment',
        description: 'Paid loan installment',
        amount: 1000,
        date: '2025-01-05',
      },
      {
        id: '13',
        userId: 'user1',
        type: 'contribution',
        description: 'Added to monthly savings',
        amount: 200,
        date: '2025-01-10',
      },
      {
        id: '14',
        userId: 'user2',
        type: 'loan',
        description: 'Took a business loan',
        amount: 10000,
        date: '2025-01-15',
      },
      {
        id: '15',
        userId: 'user2',
        type: 'payment',
        description: 'Paid partial loan installment',
        amount: 3000,
        date: '2025-01-20',
      },
  ];
  